
name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        default: "01/01/2025"
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        default: "01/02/2025"
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: barryhuang26/pull-request-analytics-action@v1
        with:
          GITHUB_TOKEN: secrets.PR_ANALYTICS_TOKEN # 必須設定
          GITHUB_REPO_FOR_ISSUE: "dd3-server" # 你的目標儲存庫名稱，例如 my-repo
          GITHUB_OWNER_FOR_ISSUE: "dudoo-team" # 目標儲存庫的擁有者，例如 my-org 或 my-username
          GITHUB_OWNERS_REPOS: "dudoo-team/dd3-server, dudoo-team/dd3-ios" # 列出擁有者和儲存庫，例如 my-org/my-repo1
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Berlin"
          SHOW_ACTIVITY_TIME_GRAPHS: true
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
